import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import DesktopLayout from '@/components/layout/DesktopLayout'
import MobileLayout from '@/components/layout/MobileLayout'
import RootClientWrapper from './RootClientWrapper'

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi-Black.otf'
    },
    {
      path: '../public/fonts/Satoshi-Bold.otf'
    },
    {
      path: '../public/fonts/Satoshi-Light.otf'
    },
    {
      path: '../public/fonts/Satoshi-Medium.otf'
    },
    {
      path: '../public/fonts/Satoshi-Regular.otf'
    }
  ],
  variable: '--font-satoshi'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${satoshi.variable} antialiased`}>
        <RootClientWrapper>{children}</RootClientWrapper>
      </body>
    </html>
  )
}
